version: "3.7"

services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  diet:
    build: .
    container_name: diet
    ports:
      - "4000:4000"
    platform: linux/amd64
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - SECRET_KEY_BASE=tekc2WiCxxNkegdToXitOJxOpRjvPViVACt+LZ//M5B4oFNTucmhMsFelP52qlSf
    volumes:
      - .:/app
